#!/usr/bin/env python3
"""
IBM FileNet Repository Audit Initialization Script

This script creates the standardized folder structure for a repository audit.
It reads the Object Store name from the MCP configuration and creates an
organized directory hierarchy for audit outputs.

Usage:
    python tools/init_audit.py [--object-store OS_NAME] [--date YYYY-MM-DD]

If no arguments provided, reads from .bob/mcp.json and uses current date.
"""

import os
import sys
import json
import argparse
from datetime import datetime
from pathlib import Path


def read_mcp_config(config_path=".bob/mcp.json"):
    """
    Read the MCP configuration file to extract Object Store name.
    
    Args:
        config_path: Path to the MCP configuration file
        
    Returns:
        str: Object Store name or None if not found
    """
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
            
        # Navigate to the Object Store configuration
        object_store = (
            config.get('mcpServers', {})
            .get('content-repository', {})
            .get('env', {})
            .get('OBJECT_STORE')
        )
        
        return object_store
    except FileNotFoundError:
        print(f"Error: MCP configuration file not found at {config_path}")
        return None
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON in {config_path}")
        return None
    except Exception as e:
        print(f"Error reading MCP config: {e}")
        return None


def create_audit_structure(object_store, audit_date=None):
    """
    Create the complete audit folder structure.
    
    Args:
        object_store: Name of the Object Store
        audit_date: Date string in DD-MM format (default: current date)
        
    Returns:
        Path: Path to the created audit directory
    """
    if audit_date is None:
        audit_date = datetime.now().strftime("%d-%m")
    
    # Create audit folder name: ObjectStore_DD-MM
    audit_folder_name = f"{object_store}_{audit_date}"
    audit_base_path = Path("audits") / audit_folder_name
    
    # Define the folder structure
    folders = [
        audit_base_path,
        audit_base_path / "reports",
        audit_base_path / "data",
        audit_base_path / "analysis",
        audit_base_path / "recommendations",
    ]
    
    # Create all folders
    for folder in folders:
        folder.mkdir(parents=True, exist_ok=True)
        print(f"✓ Created: {folder}")
    
    return audit_base_path


def create_audit_metadata(audit_path, object_store):
    """
    Create the audit metadata JSON file.
    
    Args:
        audit_path: Path to the audit directory
        object_store: Name of the Object Store
    """
    metadata = {
        "object_store": object_store,
        "audit_date": datetime.now().isoformat(),
        "audit_type": "full",
        "auditor": "Bob Repository Auditor",
        "status": "initialized",
        "created_by": "init_audit.py script"
    }
    
    metadata_path = audit_path / "audit_metadata.json"
    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=2)
    
    print(f"✓ Created: {metadata_path}")


def create_readme(audit_path, object_store):
    """
    Create a README file in the audit directory.
    
    Args:
        audit_path: Path to the audit directory
        object_store: Name of the Object Store
    """
    readme_content = f"""# Repository Audit - {object_store}

**Audit Date:** {datetime.now().strftime("%B %d, %Y")}  
**Object Store:** {object_store}  
**Status:** Initialized

## Folder Structure

```
{audit_path.name}/
├── reports/           # Executive summary and comprehensive audit reports
├── data/             # CSV files and raw data exports
├── analysis/         # Detailed analysis documents
└── recommendations/  # Actionable recommendations and roadmaps
```

## Next Steps

1. Run the Content Repository Auditor mode in Bob
2. The mode will populate these folders with audit findings
3. Review the executive summary in reports/
4. Implement recommendations from recommendations/

## Files to be Generated

### Reports
- `Executive_Summary.md` - High-level findings for stakeholders
- `Repository_Audit_Report.md` - Comprehensive detailed report

### Data
- `class_inventory.csv` - Complete class catalog
- `property_matrix.csv` - Property usage analysis
- `document_counts.csv` - Document distribution

### Analysis
- `class_analysis.md` - Document class findings
- `property_analysis.md` - Property usage patterns
- `folder_analysis.md` - Folder structure assessment

### Recommendations
- `consolidation_plans.md` - Class consolidation strategies
- `cleanup_actions.md` - Step-by-step cleanup tasks
- `implementation_roadmap.md` - Phased implementation plan

---

*Generated by init_audit.py*
"""
    
    readme_path = audit_path / "README.md"
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    
    print(f"✓ Created: {readme_path}")


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(
        description="Initialize IBM FileNet Repository Audit folder structure"
    )
    parser.add_argument(
        "--object-store",
        help="Object Store name (default: read from .bob/mcp.json)"
    )
    parser.add_argument(
        "--date",
        help="Audit date in DD-MM format (default: current date)"
    )
    parser.add_argument(
        "--config",
        default=".bob/mcp.json",
        help="Path to MCP configuration file (default: .bob/mcp.json)"
    )
    
    args = parser.parse_args()
    
    # Get Object Store name
    if args.object_store:
        object_store = args.object_store
        print(f"Using provided Object Store: {object_store}")
    else:
        print(f"Reading Object Store from {args.config}...")
        object_store = read_mcp_config(args.config)
        
        if not object_store:
            print("\nError: Could not determine Object Store name.")
            print("Please provide it using --object-store argument.")
            sys.exit(1)
        
        print(f"Found Object Store: {object_store}")
    
    # Create folder structure
    print("\nCreating audit folder structure...")
    audit_path = create_audit_structure(object_store, args.date)
    
    # Create metadata file
    print("\nCreating audit metadata...")
    create_audit_metadata(audit_path, object_store)
    
    # Create README
    print("\nCreating README...")
    create_readme(audit_path, object_store)
    
    # Success message
    print("\n" + "="*60)
    print("✓ Audit initialization complete!")
    print("="*60)
    print(f"\nAudit directory: {audit_path}")
    print("\nNext steps:")
    print("1. Open Bob and switch to Content Repository Auditor mode")
    print("2. Request a full audit")
    print("3. The mode will populate the created folders with findings")
    print("\nFolder structure:")
    print(f"  {audit_path}/")
    print(f"  ├── reports/")
    print(f"  ├── data/")
    print(f"  ├── analysis/")
    print(f"  └── recommendations/")


if __name__ == "__main__":
    main()

# Made with Bob
